/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { environment } from 'src/environments/environment';
import { Category, CreateCategoryRequest } from '../models/Category.api.model';
@Injectable({ providedIn: 'root' })
export class CategoryService {
  apiUrl = environment.apiUrl;

  constructor(private http: HttpClient) {
  }
  GetCategoryById(Id: number) {
    return this.http.get(this.apiUrl + "Category/GetCategoryById?Id=" + Id);
  }
  CreateCategory(model: CreateCategoryRequest) {
    return this.http.post(this.apiUrl + "Category/CreateCategory", model);
  }
  EditCategory(model: Category) {
    return this.http.put(this.apiUrl + "Category/EditCategory", model);
  }
  DeleteCategory(Id: number) {
    return this.http.delete(this.apiUrl + "Category/DeleteCategory?Id=" + Id);
  }
}
