/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { environment } from 'src/environments/environment';
import { Check, CreateCheckRequest } from '../models/Check.api.model';

@Injectable({ providedIn: 'root' })
export class CheckService{
  apiUrl = environment.apiUrl;
  
    constructor(private http: HttpClient) {
    }
    GetCheckById(Id: number) {
      return this.http.get(this.apiUrl + "Check/GetCheckById?Id=" + Id);
    }
    CreateCheck(model: CreateCheckRequest) {
      return this.http.post(this.apiUrl + "Check/CreateCheck", model);
    }
    EditCheck(model: Check) {
      return this.http.put(this.apiUrl + "Check/EditCheck", model);
    }
    DeleteCheck(Id: number) {
      return this.http.delete(this.apiUrl + "Check/DeleteCheck?Id=" + Id);
    }

}