/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RefreshTokenRequest {
  refreshToken: string ;
  token: string ;
}
export interface RefreshTokenResponse {
  accsesToken: string
  refreshToken: string
}
